echo "version: '3.8'

services:
  app:
    image: amedoux/gestion_etablissement:v1.0.0
    ports:
      - \"80:80\"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_etablissement
    ports:
      - \"3306:3306\"" > docker-compose.yml
